Deprecate the className prop
remarkjs/react-markdown pull request #799
Opened 2023-11-15 20:30 UTC by remcohaszing

### Initial checklist

*   [ ] I read the support docs 
*   [ ] I read the contributing guide 
*   [ ] I agree to follow the code of conduct 
*   [ ] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [ ] If applicable, I’ve added docs and tests

### Description of changes

This deprecates the `className` prop, but does not remove it yet. Users should wrap the `<Markdown>` component inside a `<div>` manually instead.

Closes #781

2023-11-16 00:24 UTC, JounQin requested changes
https://github.com/remarkjs/react-markdown/issues/781#issuecomment-1813496135

2023-11-17 09:42 UTC, remcohaszing commented
I misinterpreted the meaning of the word _deprecated_ here originally in a late evening.

I interpret _deprecated_ as _planned for change or removal_ with a warning. In this project _deprecated_ means _removed_ with an error, making deprecations semver major.

2023-11-17 10:03 UTC, remcohaszing commented
Sure :+1: 

It just feeld a bit weird to link a non-existent header from the code.

2023-11-17 10:17 UTC, wooorm commented
Ah that’s why, hmm, then I’d do a `<!-- To do: add heading for slug `deprecate-classname` -->`
Or these two comments might be enough!

2023-11-17 10:27 UTC, remcohaszing commented
Since this change is breaking, this PR shouldn’t be merged until the next major anyway. I think this PR thread is plenty reminder once this gets merged. :)

2023-11-17 10:31 UTC, wooorm approved these changes

2024-01-30 15:04 UTC, ChristianMurphy approved these changes

2025-02-20 12:43 UTC, closed without merging

2025-02-20 13:03 UTC, wooorm commented
Released in [`10.0.0`](https://github.com/remarkjs/react-markdown/releases/tag/10.0.0)!